修改build

diff --git a/build-kernel b/build-kernel
--- a/build-kernel
+++ b/build-kernel
@@ -228,10 +228,12 @@ function pack_image_build() {
         elif [[ -f ${OUT_DIR}/arch/arm64/boot/Image ]]; then
             cp ${OUT_DIR}/arch/arm64/boot/Image anykernel/kernels/$1
         else
-            tg_post_error $1
+            # tg_post_error $1
+            echo "tg_post_error"
         fi
     else
-        tg_post_error $1
+        # tg_post_error $1
+        echo "tg_post_error"
     fi
 
     cp ${OUT_DIR}/arch/arm64/boot/dtb anykernel/kernels/$1
@@ -240,7 +242,7 @@ function pack_image_build() {
 
 START=$(date +"%s")
 
-tg_post_msg
+# tg_post_msg
 
 # Set compiler Path
 if [[ "$@" =~ "gcc"* ]]; then
@@ -360,18 +362,20 @@ DIFF=$((END - START))
 cd anykernel || exit
 zip -r9 "${ZIPNAME}" ./* -x .git .gitignore ./*.zip
 
-RESPONSE=$(curl -# -F "name=${ZIPNAME}" -F "file=@${ZIPNAME}" -u :"${PD_API_KEY}" https://pixeldrain.com/api/file)
-FILEID=$(echo "${RESPONSE}" | grep -Po '(?<="id":")[^"]*')
+# RESPONSE=$(curl -# -F "name=${ZIPNAME}" -F "file=@${ZIPNAME}" -u :"${PD_API_KEY}" https://pixeldrain.com/api/file)
+# FILEID=$(echo "${RESPONSE}" | grep -Po '(?<="id":")[^"]*')
 
 CHECKER=$(find ./ -maxdepth 1 -type f -name "${ZIPNAME}" -printf "%s\n")
-if (($((CHECKER / 1048576)) > 5)); then
-    curl -s -X POST https://api.telegram.org/bot"${BOT_API_KEY}"/sendMessage -d text="✅ Kernel compiled successfully in $((DIFF / 60)) minute(s) and $((DIFF % 60)) seconds for ${DEVICE}" -d chat_id="${CI_CHANNEL_ID}" -d parse_mode=HTML
-    curl -s -X POST https://api.telegram.org/bot"${BOT_API_KEY}"/sendMessage -d text="Kernel build link: https://pixeldrain.com/u/$FILEID" -d chat_id="${CI_CHANNEL_ID}" -d parse_mode=HTML
-    #    curl -F chat_id="${CI_CHANNEL_ID}" -F document=@"$(pwd)/${ZIPNAME}" https://api.telegram.org/bot"${BOT_API_KEY}"/sendDocument
-else
-    tg_post_error
-fi
-cd "$(pwd)" || exit
+echo ${CHECKER}
+# if (($((CHECKER / 1048576)) > 5)); then
+#    curl -s -X POST https://api.telegram.org/bot"${BOT_API_KEY}"/sendMessage -d text="✅ Kernel compiled successfully in $((DIFF / 60)) minute(s) and $((DIFF % 60)) seconds for ${DEVICE}" -d chat_id="${CI_CHANNEL_ID}" -d parse_mode=HTML
+#    curl -s -X POST https://api.telegram.org/bot"${BOT_API_KEY}"/sendMessage -d text="Kernel build link: https://pixeldrain.com/u/$FILEID" -d chat_id="${CI_CHANNEL_ID}" -d parse_mode=HTML
+#    #    curl -F chat_id="${CI_CHANNEL_ID}" -F document=@"$(pwd)/${ZIPNAME}" https://api.telegram.org/bot"${BOT_API_KEY}"/sendDocument
+#else
+#    # tg_post_error
+#    echo "tg_post_error"
+#fi
+# cd "$(pwd)" || exit
 
 # Cleanup
-rm -fr anykernel/
+# rm -fr anykernel/
